---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
  labels:
    app: backend
    tier: application
type: Opaque
data:
  # Note: These should be properly encrypted in production
  POSTGRES_PASSWORD: eW91cl9wYXNzd29yZA== # base64 encoded
