# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev
  labels:
    app: postgres
    tier: database
type: Opaque
data:
  POSTGRES_PASSWORD: eW91cl9wYXNzd29yZA==
