apiVersion: v1
kind: Service
metadata:
  name: staging-service
  namespace: staging
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
